ODROID: fix compile error after v5.18
build/os_dep/osdep_service.c:1294:2: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1294 |  complete_and_exit(comp, 0);
      |  ^~~~~~~~~~~~~~~~~

This error is due to kernel patch,
[1] https://patchwork.kernel.org/project/linux-kselftest/patch/20220417110532.c0580c358f@2b220eea1db5e11/

Signed-off-by: Dongjin Kim <tobetter@gmail.com>