ODROID: fix compile error after v5.19.1
os_dep/linux/ioctl_cfg80211.c:9974:13: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, unsigned int)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *)’ [-Werror=incompatible-pointer-types]
os_dep/linux/ioctl_cfg80211.c:10254:10: error: ‘struct wireless_dev’ has no member named ‘current_bss’

This error is due to kernel patch,
	["7a53ad13c091" wifi: cfg80211: do some rework towards MLO link APIs]

Signed-off-by: Dongjin Kim <tobetter@gmail.com>