ODROID: fix compile error after v5.19.1
build/os_dep/linux/ioctl_cfg80211.c:455:2: error: too few arguments to function ‘cfg80211_ch_switch_notify’

This error is due to kernel patch,
	["7a53ad13c091" wifi: cfg80211: do some rework towards MLO link APIs]

Signed-off-by: Dongjin Kim <tobetter@gmail.com>